### ISSUE TITLE
Docker Hub Setup Instructions & `SWAGGER_HOST` Variable

### ISSUE THREAD

**Issue by J12934** [swagger-api/swagger-petstore#17]
Hi 👋

I found a small Typo in the dockerhub documentation.

The documentation on docker hub (https://hub.docker.com/r/swaggerapi/petstore) says to start the container like this:

```
docker run -d -e SWAGGER_HOST=http://petstore.swagger.io \
  -e SWAGGER_BASE_PATH=/v2 -p 80:8080 swaggerapi/swagger-petstore
```

But the docker repo ist called `swaggerapi/petstore` not `swaggerapi/swagger-petstore` so the command will fail.

The correct command should be:

```
docker run -d -e SWAGGER_HOST=http://petstore.swagger.io \
  -e SWAGGER_BASE_PATH=/v2 -p 80:8080 swaggerapi/petstore
```

On a related note, the `SWAGGER_HOST` doesn't appear to be working correctly. When starting the container like described above the swagger ui still tries to fetch the swagger.json from `http://localhost:8080/v2/swagger.json`.

**Comment by mchzawalski** [comment]
> On a related note, the SWAGGER_HOST doesn't appear to be working correctly. When starting the container like described above the swagger ui still tries to fetch the swagger.json from http://localhost:8080/v2/swagger.json.

You have to specify additional environment variable SWAGGER_URL via docker command pointing to your host url.

`-e SWAGGER_URL=http://your.domain.or.ip.and.port`

**Comment by J12934** [comment]
Ahh thank you @mchzawalski 👏
Seems that this replaces the `SWAGGER_HOST` env var completely.

Would be cool if the docker hub documentation could be changed to reflect that.

**Comment by webron** [comment]
Thanks for filing the issue. I've updated the docs to reflect the change of the docker image.

As for `SWAGGER_HOST` vs `SWAGGER_URL`, they each serve a different purpose.

Can you please verify the change and let me know if anything else should be clarified?

**Comment by J12934** [comment]
Hi
yes that has solved my initial problem, thank you 👏

When i start this like described in the documentation the swagger ui however still doesn't really work as intended, see screenshot.

<img width="1620" alt="Screenshot 2020-01-08 at 21 40 58" src="https://user-images.githubusercontent.com/13718901/72014127-95849f00-325f-11ea-83d7-f577afc65aaf.png">

What works for me is also setting the `SWAGGER_URL` to `http://localhost` like this:

```bash
docker run -d -e SWAGGER_HOST=http://petstore.swagger.io \
  -e SWAGGER_URL=http://localhost \
  -e SWAGGER_BASE_PATH=/v2 -p 80:8080 swaggerapi/petstore
```

**Comment by JonathanParrilla** [comment]
Hello @J12934 

The documentation for swaggerapi/petstore on Docker Hub has been updated to reflect the addition of the SWAGGER_URL environment variable as well as how it will affect/overwrite the value of SWAGGER_HOST.

I've also updated the example run command to match yours.

Thank you for pointing this out to us.

**Comment by J12934** [comment]
Nice 
Thank you 👏
